### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by SupremeRumHam** [McInkay/McPodcast#10]
Awesome project!! How can I use it? I already downloaded a zip file!!

**Comment by McInkay** [comment]
It's not currently ready for proper usage yet. It'll be a few weeks still. However, if you really want to try it in it's very early stage, it would depend on what OS you are using.

If Windows, download and run the exe file from the releases page.
If Max, download and run the dmg file from the releases page.
If Linux, download and run the AppImage file from the releases page.

**Comment by SupremeRumHam** [comment]
okay cool. I can wait!
